language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - AUTHOR_TESTING=1
before_install:
  - cpanm --notest Pod::Coverage::TrustPod Test::Perl::Critic Devel::Cover::Report::Coveralls
after_success:
  - cover -test -report coveralls
